planetlabs/eslint-config-planet

- config/base.json
- config/react.json
react/jsx-quotes [has been deprecated](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-quotes.md) in favor of [jsx-quotes](http://eslint.org/docs/rules/jsx-quotes).
> Replace deprecated react/jsx-quotes with jsx-quotes

- config/base.json
Most of the code we have currently indents switch cases by one level.
> One level of indentation for switch case

- index.js
- package.json
- react.js
This suggests adding a few rules at the error level (so will require a major version bump).
List of changes with motivation
* [`array-callback-return`](http://eslint.org/docs/rules/array-callback-return) - e.g. keeps people from using `map` inappropriately
* [`arrow-parens`](http://eslint.org/docs/rules/arrow-parens) - with the "as-needed" option, this conforms to our current use (e.g. `foo.map(item => item.id)` and `foo.map((item, index) => index)` only has parens around args where needed)
* [`react/jsx-wrap-multilines`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-wrap-multilines.md) - enforces consistency with our current style
* [`react/no-array-index-key`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md) - …
> Updated base and React config

- package.json
There are changes coming in minor and patch releases for Prettier that are "breaking" from our perspective (e.g. prettier/prettier#1344).  We can bump major versions here when we want to upgrade Prettier.
I'll release this as a patch so builds are fixed where we are depending on `eslint-config-planet@13`.
> Peg prettier to avoid breaking changes

- react.js
We've found that this rule produces false positives (and have disabled it in a number of places).  I don't think we risk anything by no longer enforcing it.
> Remove the react/no-multi-comp rule

- index.js
From ESLint rule page:
> The `--fix` option on the command line can automatically fix some of the problems reported by this rule.
> If a variable is never reassigned, using the `const` declaration is better.
> `const` declaration tells readers, “this variable is never reassigned,” reducing cognitive load and improving maintainability.
Link to rule: https://eslint.org/docs/rules/prefer-const
> Enforce `prefer-const`

- package-lock.json
- package.json
Upgrades, especially to resolve incompatibility with latest atom:
https://github.com/prettier/prettier-atom/issues/268#issuecomment-329789268
> chore: upgrade eslint and prettier packages

- index.js
- Raise errors when arguments are unused
- Allow to use rest operator to discard unwanted siblings
> Tweak `no-unused-vars` rule

- index.js
- don't allow function parameter re-assignment, even nested ones: https://eslint.org/docs/rules/no-param-reassign
In almost all cases, you don't want to be mutating the object reference of the argument of a function. That prevents functions from being pure, and can have unexpected side effects. This linter rule catches most common accidental mutations.
This can still be accidentally defeated, such as in the following example, so you still have to be careful with what you're doing, and think whether shallow object copies are what you want to do:
```javascript
function getObjectsWithArea(objects) {
const newObjects = {...objects}; // this is a shallow copy!!
for (const object in objects) {
// Oops, we're actually reassigning a value referenced by the 'objects' arg.
// Accidental side …
```
> feat: don't allow function param reassignment

- index.js
- package-lock.json
- package.json
Adds `eslint-plugin-import`, with the following rules:
- `import/no-unresolved` (
Ensures an imported module can be resolved to a module on the local filesystem, as defined by standard Node require.resolve behavior.)
- `import/named` (
Verifies that all named imports are part of the set of named exports in the referenced module.)
- `import/default` (
If a default import is requested, this rule will report if there is no default export in the imported module.)
> feat: add import plugin

- examples/es6/.eslintrc
- examples/react/.eslintrc
- examples/react/component.js
- index.js
- package-lock.json
- package.json
- react.js
- readme.md
This adds [`react-hooks` rules](https://www.npmjs.com/package/eslint-plugin-react-hooks).  The `exhaustive-deps` rule is very nice, but it can be awkward at times if you are not always destructuring props, so it is set to "warn" level.
I added `eslint-plugin-react` and a couple other "conditional" dependencies as proper dependencies.  These aren't actually required when using the vanilla `planet` rules, but they simplify the setup story when using the `planet/react` rules.
> Add rules for hooks, import order, and no-var

- index.js
- package-lock.json
- package.json
The update to prettier@2 brings a number of "breaking" changes.  To maintain backwards compatibility regarding handling of arguments for arrow functions, I've added the `arrowParens: 'avoid'` option.  This makes it so single arguments are not wrapped in parens (which was the behavior with prettier@1.
I've also added the [`no-const-assign` rule](https://eslint.org/docs/rules/no-const-assign).  This one catches actual bugs.
> Updated deps, add `no-const-assign`

- examples/es6/local-module.js
- examples/es6/main.js
- examples/react/component.js
- index.js
- package-lock.json
- react.js
I was wrong about the sorts import, we still need it. 👍 
- Moved import sorting and order to main ruleset
- Since we talk about sorting, I sorted the rules alphabetically (they were kinda but not fully)
- Converted es6 main.js to es6 and added local import
- Converted react function to variable holding arrow function
I did *not* change the version number, how do you feel about bumping it? Major, minor?
If you are fine with the PR feel free to bump it at your discretion, so we don't need another earth cycle 😄
> Move import sorting to main ruleset

- index.js
WRONG
```js
import {foo} from 'fooPackage';
import {bar} from 'barPackage';
import {baz} from 'fooPackage';
```
RIGHT
```js
import {foo, baz} from 'fooPackage';
import {bar} from 'barPackage';
```
> Avoid duplicate and self imports

- index.js
WRONG
```js
import foo from './foo';
// some module-level initializer
initWith(foo);
import bar from './bar';
```
RIGHT
```js
import foo from './foo';
import bar from './bar';
// some module-level initializer
initWith(foo);
```
> Always have imports first

- .npmignore
- package.json
Having a list of allowed files is more straightforward to maintain than a list of excluded files (assuming many people publishing from different environments).  Too bad npm doesn't respect a global git excludes file (npm/npm#5673).
This is an alternative to and closes #43.
```
npm pack
```
```
npm notice 
npm notice 📦  eslint-config-planet@20.0.0
npm notice === Tarball Contents === 
npm notice 2.4kB index.js    
npm notice 1.1kB react.js    
npm notice 1.2kB package.json
npm notice 4.6kB readme.md   
npm notice === Tarball Details === 
npm notice name:          eslint-config-planet                    
npm notice version:       20.0.0                                  
npm notice filename:      eslint-config-planet-20.0.0.tgz         
npm notice package size:  3.4 kB …
```
> Configure a list of files to be included in the package

- index.js
- react.js
This adds in the [`no-constant-binary-expression`](https://eslint.org/docs/latest/rules/no-constant-binary-expression) and [`react/jsx-curly-brace-presence`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md) rules.
> Additional rules

- react.js
Adds ".jsx" as a file override for default scanning.
> Add .jsx as default file extension to scan in addition to .js

- examples/es6/main.js
- index.js
- react.js
This makes use of the [`import/extensions` rule](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/extensions.md).
> Require file extensions in import specifiers

- index.js
This makes it more likely that people will use this configuration.
> Ignore file extension on imports specifiers for packages

- eslint.config.js
- index.js
- package-lock.json
- package.json
- react.js
- readme.md
Updates to eslint flat configs and enforces a minimum version of eslint v9. This should be published as a new major version once merged.
Followed the [migration guide](https://eslint.org/docs/latest/use/configure/migration-guide) and made use of the migrator to convert the existing configurations.
> Update to eslint v9 flat config

- package-lock.json
- package.json
The latest release of eslint-plugin-react-hooks incorrectly flags uses of hooks as occurring in a loop if a component function body contains a loop.
Downgrading to version 5.0.0 is a workaround until the React team publishes a release with the fix in https://github.com/facebook/react/pull/28714 (merged but not yet released).
See https://github.com/facebook/react/issues/31687
> Downgrade eslint-plugin-react-hooks

- examples/es6/main.js
- examples/react/component.js
- index.js
- package-lock.json
- package.json
- react.js
This replaces use of the [`eslint-plugin-sort-imports-es6-autofix` package](https://www.npmjs.com/package/eslint-plugin-sort-imports-es6-autofix) with the [`import/order` rule](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md) from the [`eslint-plugin-import` package](https://www.npmjs.com/package/eslint-plugin-import).
As can be seen in the diff, the import order enforced between the two packages is not the same. But the `eslint-plugin-import` package works with ESLint 9 and the `eslint-plugin-sort-imports-es6-autofix` is not actively maintained.
> Configure import sorting

- examples/react/component.tsx
- react.js
Addition of Typescript extensions to files array extends linting for `planet/react` rules to Typescript files too.
> Add ts,tsx file extensions support to planet/react
